R = im2double(imread("SanFranPeak_red.pgm"));
G = im2double(imread("SanFranPeak_green.pgm"));
B = im2double(imread("SanFranPeak_blue.pgm"));
I = cat(3, R, G, B);
J1 = mat2gray(2*G - R - B);
J2 = mat2gray(R - B);
J3 = mat2gray(2*B - R - G);
J4 = mat2gray(2*R - G - B);
subplot(2, 4, 1);
imshow(R);
subplot(2, 4, 2);
imshow(G);
subplot(2, 4, 3);
imshow(B);
subplot(2, 4, 4);
imshow(I);
subplot(2, 4, 5);
imshow(J1);
subplot(2, 4, 6);
imshow(J2);
subplot(2, 4, 7);
imshow(J3);
subplot(2, 4, 8);
imshow(J4);