I = imread("Chess_noise.pgm");
K = imread("Chess.pgm");
subplot(3, 6, 1);
imshow(I);
subplot(3, 6, 2);
imshow(I);
subplot(3, 6, 3);
imshow(I);
subplot(3, 6, 4);
imshow(I);
subplot(3, 6, 5);
imshow(I);
subplot(3, 6, 6);
imshow(I);
N1 = logical(im2bw(mat2gray(fspecial("disk", 1)), 0.4));
N2 = logical(im2bw(mat2gray(fspecial("disk", 2)), 0.4));
N3 = logical(im2bw(mat2gray(fspecial("disk", 3)), 0.4));
N4 = logical(im2bw(mat2gray(fspecial("disk", 4)), 0.4));
N5 = logical(im2bw(mat2gray(fspecial("disk", 5)), 0.4));
N6 = logical(im2bw(mat2gray(fspecial("disk", 6)), 0.4));
subplot(3, 6, 7);
imshow(N1);
subplot(3, 6, 8);
imshow(N2);
subplot(3, 6, 9);
imshow(N3);
subplot(3, 6, 10);
imshow(N4);
subplot(3, 6, 11);
imshow(N5);
subplot(3, 6, 12);
imshow(N6);
J1 = medfilt2(I, N1);
J2 = medfilt2(I, N2);
J3 = medfilt2(I, N3);
J4 = medfilt2(I, N4);
J5 = medfilt2(I, N5);
J6 = medfilt2(I, N6);
subplot(3, 6, 13);
imshow(J1);
subplot(3, 6, 14);
imshow(J2);
subplot(3, 6, 15);
imshow(J3);
subplot(3, 6, 16);
imshow(J4);
subplot(3, 6, 17);
imshow(J5);
subplot(3, 6, 18);
imshow(J6);

fprintf("RMS error for J1 is %6.2f\n", sqrt(sum(sum(imsubtract(K, J1).^2))/prod(size(I))));
fprintf("RMS error for J2 is %6.2f\n", sqrt(sum(sum(imsubtract(K, J2).^2))/prod(size(I))));
fprintf("RMS error for J3 is %6.2f\n", sqrt(sum(sum(imsubtract(K, J3).^2))/prod(size(I))));
fprintf("RMS error for J4 is %6.2f\n", sqrt(sum(sum(imsubtract(K, J4).^2))/prod(size(I))));
fprintf("RMS error for J5 is %6.2f\n", sqrt(sum(sum(imsubtract(K, J5).^2))/prod(size(I))));
fprintf("RMS error for J6 is %6.2f\n", sqrt(sum(sum(imsubtract(K, J6).^2))/prod(size(I))));